name: docscanner
description: A Flutter Document Scanner

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  camera: ^0.10.5
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  pdf: ^3.10.4
  image: ^4.1.3
  flutter_secure_storage: ^9.0.0
  file_selector: ^1.0.3
  edge_detection:
    path: plugins/edge_detection

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  